### ISSUE TITLE
Really want to fling this

### ISSUE THREAD

**Issue by sethladd** [bramvbilsen/Flutter-Fidget-Spinner-App-Animations-#1]
Can you allow me to fling the spinner to, well, spin it? :)

**Comment by bramvbilsen** [comment]
@sethladd Aha, great idea! I'm on vacation atm so I can't add it right away, but I'll add the feature once I find the time!

**Comment by bramvbilsen** [comment]
Added a simple gesture detector that spins the fidget spinner.

**Comment by sethladd** [comment]
Cool! Looking forward to trying it out!
